/**
 * RevenueByCategory component displays the revenue generated by different categories.
 * It fetches event categories and revenue data, and shows a bar chart based on the selected year.
 * 
 * @component
 */

import { DatePicker, Space } from 'antd';
import dayjs from 'dayjs';
import React, { useCallback,useEffect, useState } from 'react';
import { useTranslation } from "react-i18next";
import { useDispatch, useSelector } from 'react-redux';

import { categoryRevenueList } from '../../redux/dashboardSlice';
import { eventCategoryDetails } from "../../redux/eventSlice"
import Card from '../card/card';
import ApexChartComponent from '../chart/chart';

const RevenueByCategory = () => {
    const dispatch = useDispatch();
    const { categoryrevenue: revenueData, loading } = useSelector((state) => state.dashboardSlice) || [];
    const categories = useSelector((state) => state.eventSlice.eventCategory) || [];
    const [series, setSeries] = useState([]);
    const { t } = useTranslation();
    const [selectedYear, setSelectedYear] = useState(dayjs().year());
    const [yearMoment, setYearMoment] = useState(dayjs().year(selectedYear));

    // First useEffect to fetch categories
    useEffect(() => {
        dispatch(eventCategoryDetails());
    }, [dispatch]);

    // Memoized function to fetch revenue data
    const fetchRevenueData = useCallback((year) => {
        dispatch(categoryRevenueList({ 
            date: dayjs().year(year).format('YYYY-MM-DD') 
        }));
    }, [dispatch]);

    // Effect for revenue data
    useEffect(() => {
        fetchRevenueData(selectedYear);
    }, [selectedYear, fetchRevenueData]);

    useEffect(() => {
        if (!Array.isArray(revenueData)) {
            console.error('Expected revenueData to be an array:', revenueData);
            return;
        }

        const yearData = revenueData.filter(item => item.year === selectedYear);

        const seriesData = [{
            name: 'Revenue',
            data: categories.map(category => {
                const categoryRevenue = yearData.find(item => 
                    item.categoryId === category._id
                );
                return categoryRevenue ? categoryRevenue.totalRevenue : 0;
            })
        }];

        setSeries(seriesData);
    }, [revenueData, categories, selectedYear]);

    const handleYearChange = (date) => {
        if (!date) return;
        
        const newYear = date.year();
        setSelectedYear(newYear);
        setYearMoment(dayjs().year(newYear));
    };

    const options = {
        chart: {
            type: 'bar',
            height: 390,
            toolbar: { show: false },
        },
        xaxis: {
            categories: categories.map(cat => cat.name),
            labels: {
                rotate: -45,
                style: {
                    colors: '#757575',
                    fontSize: '14px',
                    fontWeight: "400"
                }
            },
        },
        yaxis: {
            labels: {
                style: {
                    colors: '#757575',
                    fontSize: '12px',
                    fontWeight: "400"
                },
                formatter: function (value) {
                    return `$${value.toLocaleString()}`;
                }
            }
        },
        tooltip: {
            enabled: true,
            shared: false,
            intersect: true,
            y: {
                formatter: function (value) {
                    return `$${value.toLocaleString()}`;
                }
            },
            marker: {
                show: true,
            }
        },
        plotOptions: {
            bar: {
                borderRadius: 5,
                columnWidth: '30px',
            }
        },
        stroke: {
            width: 2,
            colors: ['#FF9900'],
        },
        colors: ['#FF9900'],
        dataLabels: {
            enabled: false
        },
        markers: {
            size: 3,
            strokeWidth: 0,
            hover: {
                size: 6,
                sizeOffset: 0
            }
        },
        states: {
            hover: {
                filter: {
                    type: 'none',
                }
            }
        }
    };

    return (
        <div className='mb-4'>
            <div>
                <Card loading={loading}>
                    <div>
                        <div className='event-Containers'>
                            <h3>{t("REVENUE_BY_CATEGORY")}</h3>
                            <Space direction="vertical">
                                <DatePicker
                                    className='form-event-control'
                                    onChange={handleYearChange}
                                    picker="year"
                                    value={yearMoment}
                                    mode="year"
                                />
                            </Space>
                        </div>
                        {series.length > 0 && categories.length > 0 ? (
                            <div className='bar-chart-height'>
                                <ApexChartComponent
                                    type="bar"
                                    series={series}
                                    options={options}
                                    height={390}
                                />
                            </div>
                        ) : (
                            <div className='NoEventList'>{t("NO_DATA_AVAILABLE")}</div>
                        )}
                    </div>
                </Card>
            </div>
        </div>
    );
};

export default RevenueByCategory;